name: build-linux
on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CXX: g++-11
    steps:
      - name: Install GCC11 and other stuffs
        run: |
          sudo apt update
          sudo apt install g++-11
          sudo apt install libx11-dev libxft-dev libxext-dev
          sudo apt install libgl1-mesa-dev

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'gcc-vcpkg-submodule'
          buildPreset: 'gcc-vcpkg-submodule'
          buildPresetCmdString: "[`--build`, `--preset`, `$[env.BUILD_PRESET_NAME]`, `--config`, `Release`]"
          testPreset: 'gcc-vcpkg-submodule'
          testPresetCmdString: "[`--preset`, `$[env.TEST_PRESET_NAME]`, `-C`, `Release`]"
